name: 4 - using actions

on: push

jobs:
  build:
    runs-on: ubuntu-lates
    steps:
      - name: Checkout-latest
        uses: action/checkout@v4
      - name: Run Echo
        run: echo "echo echo"


      # runs-on: ubuntu-latest
      # steps:
      #     - name: Checkout Code
      #       uses: actions/checkout@v4
      #     - name: Run Echo
      #       run: echo "echo echo"
            
